name: 'Deploy thiscovery'
description: 'Deploys thiscovery stack'
inputs:
  template_name:
    description: 'Packaged template artifact name'
    required: true
  deployment_role:
    description: 'AWS role to assume'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - uses: aws-actions/setup-sam@v2
    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.template_name }}

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r requirements.txt

    - name: Deploy using thiscovery script
      shell: bash
      run: |
        thiscovery deploy ${{ env.STACK_NAME }}